<div class="display-4 mb-4">
	"<?php echo $quote->getText(); ?>"
</div>

<div class="alert bg-dark bg-dark">
	<h4>
		<span class="text-warning font-weight-bold">Filme: </span>
		<span class="text-white"><?php echo $quote->getMovie(); ?></span>
	</h4>
</div>

<!-- modal -->
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
	    	<div class="modal-header">
		        <h4 class="modal-title font-weight-bold">
		        	Sobre este projeto
		        </h4>
		        
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		     </div>
		      
		    <div class="modal-body">
		        <div class="alert alert-info">
		        	Este projeto é um portifólio.
		        </div>
		    </div>
	    </div>
	</div>
</div>