<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:300">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="/assets/css/style.css">
        <title>Frases de filmes</title>
    </head>

    <body class="wrapper">
        <div class="ct-align-center text-center mt-5">
            <header class="bg-primary p-3 text-white">
                <h1 class="font-weight-bold">
                    Frases de filmes
                </h1>

                <a href="/" class="btn btn-lg btn-success">Ver frase</a>
                <a href="/list" class="btn btn-lg btn-success">Lista com todas as frases</a>
            </header>

            <div class="jumbotron">
                <?php echo $content; ?>

                <hr>

                <div class="mb-2">
                    Desenvolvido por 
                    <a href="https://github.com/raphael-da-silva">Raphael da Silva</a>
                </div>

                 <button class="btn btn-primary font-weight-bold" id="project-info">
                    informações do projeto
                </button>
            </div>
        </div>

        <!-- modal -->
        <div class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title font-weight-bold">
                            Sobre este projeto
                        </h4>
                        
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                     </div>
                      
                    <div class="modal-body">
                        <div class="alert alert-info">
                            Este projeto é um portifólio.
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="/assets/js/app.js"></script>
    </body>
</html>
